[package]
name = "ropediff"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]

[dependencies]
xi-rope = { path = "../xi-mac/xi-editor/rust/rope" }
serde = "1"
serde_json = "1"
atty = "0.2"
crossbeam = "0.4"
suffix = "1"
memchr = "2.0"
statrs = "0.9"

